---
services:
  # TODO: Add proper service name
  ${SERVICE_NAME}:
    build:
      dockerfile: ./.devcontainer/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - pubsub
    volumes:
      - ./src:/app/src
  pubsub:
    image: messagebird/gcloud-pubsub-emulator
    environment:
      - PUBSUB_PROJECT1=${PUB_SUB_PROJECT_ID},${PUB_SUB_TOPIC}:${PUB_SUB_SUBSCRIPTION}
    healthcheck:
      test: curl -fsS http://localhost:8681 || exit 1
      retries: 2
      interval: 10s
      start_period: 5s
      timeout: 5s
    ports:
      - 8681:8681
