---
services:
  # TODO: Add proper service name
  ${SERVICE_NAME}:
    build:
      dockerfile: Dockerfile.dev
    # environment:
    #   ENVIRONMENT_KEY: ${ENVIRONMENT_IN_DOT_ENV}
    ports:
      - 8080:8080
    volumes:
      - ./src:/app/src
