---
services:
  # TODO: Add proper service name
  ${SERVICE_NAME}:
    build:
      dockerfile: Dockerfile.dev
    # environment:
    #   ENVIRONMENT_KEY: ${ENVIRONMENT_IN_DOT_ENV}
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - phpmyadmin
    volumes:
      - ./src:/app/src
  mysql:
    image: mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_TCP_PORT=${DB_PORT}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${DB_PORT}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql

volumes:
  mysql-data:
