---
services:
  pubsub:
    image: messagebird/gcloud-pubsub-emulator
    environment:
      - PUBSUB_PROJECT1=${PUB_SUB_PROJECT_ID},${PUB_SUB_TOPIC}:${PUB_SUB_SUBSCRIPTION}
    healthcheck:
      test: curl -fsS http://localhost:8681 || exit 1
      retries: 2
      interval: 10s
      start_period: 5s
      timeout: 5s
    ports:
      - 8681:8681
  api:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.dev
    environment:
      - PUB_SUB_EMULATOR_HOST=${PUB_SUB_EMULATOR_HOST}
      - PUB_SUB_PROJECT_ID=${PUB_SUB_PROJECT_ID}
      - PUB_SUB_TOPIC=${PUB_SUB_TOPIC}
      - PUB_SUB_SUBSCRIPTION=${PUB_SUB_SUBSCRIPTION}
      - PUB_SUB_PATTERN=${PUB_SUB_PATTERN}
      - PUB_SUB_PUSH_ENDPOINT=${PUB_SUB_PUSH_ENDPOINT}
    ports:
      - 8080:8080
    depends_on:
      - pubsub
    volumes:
      - ./src:/app/src
